from pathlib import Path
from typing import List

try:
    from pptx import Presentation
    from pptx.util import Pt
except Exception:  # pragma: no cover
    Presentation = None  # type: ignore[assignment]
    Pt = None  # type: ignore[assignment]


def generate_pptx_from_summary(run_id: str, title: str, sections: List[str], out_dir: str) -> str:
    output_dir = Path(out_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if Presentation is None or Pt is None:
        fallback_path = output_dir / f"{run_id}.md"
        lines = [f"# {title}", "", "Generated by AgentGCS", ""]
        for idx, sec in enumerate(sections, start=1):
            lines.append(f"## Section {idx}")
            lines.append(sec.strip())
            lines.append("")
        fallback_path.write_text("\n".join(lines), encoding="utf-8")
        return str(fallback_path.resolve())

    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_tf = slide.shapes.title
    subtitle_tf = slide.placeholders[1]
    title_tf.text = title
    subtitle_tf.text = "Generated by AgentGCS"

    for sec in sections:
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        shapes = slide.shapes
        title = shapes.title
        body = shapes.placeholders[1].text_frame
        lines = [l.strip() for l in sec.split("\n") if l.strip()]
        title.text = lines[0][:60]
        body.clear()
        for line in lines[1:6]:
            p = body.add_paragraph()
            p.text = line[:240]
            p.font.size = Pt(14)

    out_path = str((output_dir / f"{run_id}.pptx").resolve())
    prs.save(out_path)
    return out_path
