from typing import List
from pptx import Presentation
from pptx.util import Inches, Pt


def generate_pptx_from_summary(run_id: str, title: str, sections: List[str], out_dir: str) -> str:
    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_tf = slide.shapes.title
    subtitle_tf = slide.placeholders[1]
    title_tf.text = title
    subtitle_tf.text = "Generated by AgentGCS"

    for sec in sections:
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        shapes = slide.shapes
        title = shapes.title
        body = shapes.placeholders[1].text_frame
        lines = [l.strip() for l in sec.split("\n") if l.strip()]
        title.text = lines[0][:60]
        body.clear()
        for line in lines[1:6]:
            p = body.add_paragraph()
            p.text = line[:240]
            p.font.size = Pt(14)

    out_path = f"{out_dir.rstrip('/')}/{run_id}.pptx"
    prs.save(out_path)
    return out_path
